# Other Useful Methods

Before we cover the more 'complex' methods, there are several more fairly simple yet powerful methods that you should be aware of as the y are used very frequently.

* `count`, `describe`, `rank`, `nunique`, `sort_values`, `sort_index`, `dropna`
* `idxmin`, `idxmax`, `sample`, `replace`, `isin`

### Objectives
* Look at docstrings of methods
* Know the possible values of the parameters
* Method chaining
* Tricks to get the documentation when method chaining

In [4]:
import pandas as pd
pd.options.display.max_columns = 50

In [5]:
college = pd.read_csv('data/college.csv', index_col='INSTNM')
college.head()

,CITY,STABBR,HBCU,MENONLY,WOMENONLY,RELAFFIL,SATVRMID,SATMTMID,DISTANCEONLY,UGDS,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,PPTUG_EF,CURROPER,PCTPELL,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GRAD_DEBT_MDN_SUPP
INSTNM,,,,,,,,,,,,,,,,,,,,,,,,,,
Alabama A & M University,Normal,AL,1.0,0.0,0.0,0,424.0,420.0,0.0,4206.0,0.0333,0.9353,0.0055,0.0019,0.0024,0.0019,0.0000,0.0059,0.0138,0.0656,1,0.7356,0.8284,0.1049,30300,33888
University of Alabama at Birmingham,Birmingham,AL,0.0,0.0,0.0,0,570.0,565.0,0.0,11383.0,0.5922,0.2600,0.0283,0.0518,0.0022,0.0007,0.0368,0.0179,0.0100,0.2607,1,0.3460,0.5214,0.2422,39700,21941.5
Amridge University,Montgomery,AL,0.0,0.0,0.0,1,NaN,NaN,1.0,291.0,0.2990,0.4192,0.0069,0.0034,0.0000,0.0000,0.0000,0.0000,0.2715,0.4536,1,0.6801,0.7795,0.8540,40100,23370
University of Alabama in Huntsville,Huntsville,AL,0.0,0.0,0.0,0,595.0,590.0,0.0,5451.0,0.6988,0.1255,0.0382,0.0376,0.0143,0.0002,0.0172,0.0332,0.0350,0.2146,1,0.3072,0.4596,0.2640,45500,24097
Alabama State University,Montgomery,AL,1.0,0.0,0.0,0,425.0,430.0,0.0,4811.0,0.0158,0.9208,0.0121,0.0019,0.0010,0.0006,0.0098,0.0243,0.0137,0.0892,1,0.7347,0.7554,0.1270,26600,33118.5

### `count`
Counts the number of non-missing values

In [3]:
college.count()

CITY                  7535
STABBR                7535
HBCU                  7164
MENONLY               7164
WOMENONLY             7164
RELAFFIL              7535
SATVRMID              1185
SATMTMID              1196
DISTANCEONLY          7164
UGDS                  6874
UGDS_WHITE            6874
UGDS_BLACK            6874
UGDS_HISP             6874
UGDS_ASIAN            6874
UGDS_AIAN             6874
UGDS_NHPI             6874
UGDS_2MOR             6874
UGDS_NRA              6874
UGDS_UNKN             6874
PPTUG_EF              6853
CURROPER              7535
PCTPELL               6849
PCTFLOAN              6849
UG25ABV               6718
MD_EARN_WNE_P10       6413
GRAD_DEBT_MDN_SUPP    7503
dtype: int64

### `describe`
Provides summary statistics for each column. Defaults to just numeric

In [12]:
college.describe().T

,count,mean,std,min,25%,50%,75%,max
HBCU,7164.0,0.014238,0.118478,0.0,0.000000,0.00000,0.000000,1.0000
MENONLY,7164.0,0.009213,0.095546,0.0,0.000000,0.00000,0.000000,1.0000
WOMENONLY,7164.0,0.005304,0.072642,0.0,0.000000,0.00000,0.000000,1.0000
RELAFFIL,7535.0,0.190975,0.393096,0.0,0.000000,0.00000,0.000000,1.0000
SATVRMID,1185.0,522.819409,68.578862,290.0,475.000000,510.00000,555.000000,765.0000
SATMTMID,1196.0,530.765050,73.469767,310.0,482.000000,520.00000,565.000000,785.0000
DISTANCEONLY,7164.0,0.005583,0.074519,0.0,0.000000,0.00000,0.000000,1.0000
UGDS,6874.0,2356.837940,5474.275871,0.0,117.000000,412.50000,1929.500000,151558.0000
UGDS_WHITE,6874.0,0.510207,0.286958,0.0,0.267500,0.55570,0.747875,1.0000
UGDS_BLACK,6874.0,0.189997,0.224587,0.0,0.036125,0.10005,0.257700,1.0000
UGDS_HISP,6874.0,0.161635,0.221854,0.0,0.027600,0.07140,0.198875,1.0000
UGDS_ASIAN,6874.0,0.033544,0.073777,0.0,0.002500,0.01290,0.032700,0.9727
UGDS_AIAN,6874.0,0.013813,0.070196,0.0,0.000000,0.00260,0.007300,1.0000
UGDS_NHPI,6874.0,0.004569,0.033125,0.0,0.000000,0.00000,0.002500,0.9983
UGDS_2MOR,6874.0,0.023950,0.031288,0.0,0.000000,0.01750,0.033900,0.5333
UGDS_NRA,6874.0,0.016086,0.050172,0.0,0.000000,0.00000,0.011700,0.9286
UGDS_UNKN,6874.0,0.045181,0.093440,0.0,0.000000,0.01430,0.045400,0.9027
PPTUG_EF,6853.0,0.226639,0.246470,0.0,0.000000,0.15040,0.376900,1.0000
CURROPER,7535.0,0.923291,0.266146,0.0,1.000000,1.00000,1.000000,1.0000
PCTPELL,6849.0,0.530643,0.225544,0.0,0.357800,0.52150,0.712900,1.0000
PCTFLOAN,6849.0,0.522211,0.283616,0.0,0.332900,0.58330,0.745000,1.0000
UG25ABV,6718.0,0.410021,0.228939,0.0,0.241500,0.40075,0.572275,1.0000

In [5]:
# can choose data type(s)
college.describe(include='object')

            CITY STABBR    MD_EARN_WNE_P10 GRAD_DEBT_MDN_SUPP
count       7535   7535               6413               7503
unique      2514     59                598               2038
top     New York     CA  PrivacySuppressed  PrivacySuppressed
freq          87    773                822               1510

### sort_values by one or more columns

In [6]:
# ascending
college.sort_values('UGDS').head()

,CITY,STABBR,HBCU,MENONLY,WOMENONLY,RELAFFIL,SATVRMID,SATMTMID,DISTANCEONLY,UGDS,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,PPTUG_EF,CURROPER,PCTPELL,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GRAD_DEBT_MDN_SUPP
INSTNM,,,,,,,,,,,,,,,,,,,,,,,,,,
Education and Technology Institute,Greensburg,PA,0.0,0.0,0.0,0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0,0.5333,0.0000,0.9333,NaN,NaN
Taft University System,Denver,CO,0.0,0.0,0.0,0,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1,0.0000,0.0000,1.0000,NaN,PrivacySuppressed
Prince Institute-Rocky Mountains,Westminster,CO,0.0,0.0,0.0,1,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0,0.6923,0.9487,0.8824,33400,20992
Lyme Academy College of Fine Arts,Old Lyme,CT,0.0,0.0,0.0,1,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1,0.4416,0.6623,0.1429,PrivacySuppressed,PrivacySuppressed
American Conservatory Theater,San Francisco,CA,0.0,0.0,0.0,0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1,NaN,NaN,NaN,PrivacySuppressed,PrivacySuppressed

In [7]:
# descending
college.sort_values('UGDS', ascending=False).head()

,CITY,STABBR,HBCU,MENONLY,WOMENONLY,RELAFFIL,SATVRMID,SATMTMID,DISTANCEONLY,UGDS,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,PPTUG_EF,CURROPER,PCTPELL,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GRAD_DEBT_MDN_SUPP
INSTNM,,,,,,,,,,,,,,,,,,,,,,,,,,
University of Phoenix-Arizona,Tempe,AZ,0.0,0.0,0.0,0,NaN,NaN,0.0,151558.0,0.3098,0.1555,0.0760,0.0082,0.0042,0.0050,0.1131,0.0131,0.3152,0.0000,1,0.6009,0.5920,NaN,NaN,33000
Ivy Tech Community College,Indianapolis,IN,0.0,0.0,0.0,0,NaN,NaN,0.0,77657.0,0.7054,0.1523,0.0664,0.0152,0.0042,0.0000,0.0209,0.0003,0.0354,0.6350,1,0.5153,0.3384,0.4780,29400,13000
Miami Dade College,Miami,FL,0.0,0.0,0.0,0,NaN,NaN,0.0,61470.0,0.0599,0.1657,0.6805,0.0089,0.0007,0.0006,0.0035,0.0521,0.0280,0.5824,1,0.5399,0.0921,0.3503,30100,8500
Lone Star College System,The Woodlands,TX,0.0,0.0,0.0,0,NaN,NaN,0.0,59920.0,0.3226,0.1892,0.3527,0.0569,0.0024,0.0000,0.0281,0.0190,0.0292,0.6863,1,0.3405,0.1984,0.3201,32900,11000
Houston Community College,Houston,TX,0.0,0.0,0.0,0,NaN,NaN,0.0,58084.0,0.1430,0.3182,0.3161,0.0926,0.0020,0.0022,0.0151,0.0911,0.0198,0.7027,1,0.6680,0.3348,0.4751,32500,10750

In [8]:
# use a list to sort multiple columns
college.sort_values(['STABBR', 'UGDS']).head()

,CITY,STABBR,HBCU,MENONLY,WOMENONLY,RELAFFIL,SATVRMID,SATMTMID,DISTANCEONLY,UGDS,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,PPTUG_EF,CURROPER,PCTPELL,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GRAD_DEBT_MDN_SUPP
INSTNM,,,,,,,,,,,,,,,,,,,,,,,,,,
Alaska Bible College,Palmer,AK,0.0,0.0,0.0,1,NaN,NaN,0.0,27.0,0.8519,0.0000,0.0370,0.0000,0.0741,0.0000,0.0370,0.0000,0.0000,0.1481,1,0.3571,0.2857,0.4286,NaN,PrivacySuppressed
Alaska Christian College,Soldotna,AK,0.0,0.0,0.0,1,NaN,NaN,0.0,68.0,0.0588,0.0000,0.0147,0.0000,0.7794,0.0000,0.0147,0.0000,0.1324,0.0735,1,0.8868,0.6792,0.2264,NaN,PrivacySuppressed
Ilisagvik College,Barrow,AK,0.0,0.0,0.0,0,NaN,NaN,0.0,109.0,0.1376,0.0183,0.0092,0.0826,0.6881,0.0459,0.0000,0.0183,0.0000,0.6239,1,0.1323,0.0000,0.6498,24900,PrivacySuppressed
Alaska Pacific University,Anchorage,AK,0.0,0.0,0.0,1,555.0,503.0,0.0,275.0,0.5309,0.0291,0.0364,0.0255,0.1855,0.0109,0.0945,0.0000,0.0873,0.3745,1,0.3152,0.5297,0.4910,47000,23250
Alaska Career College,Anchorage,AK,0.0,0.0,0.0,0,NaN,NaN,0.0,479.0,0.3800,0.0960,0.1002,0.1983,0.1733,0.0084,0.0334,0.0000,0.0104,0.0000,1,0.7078,0.7860,0.5612,28700,8994

In [9]:
# use a list to sort multiple columns with one ascending the other descending
college.sort_values(['STABBR', 'UGDS'], ascending=[True, False]).head()

,CITY,STABBR,HBCU,MENONLY,WOMENONLY,RELAFFIL,SATVRMID,SATMTMID,DISTANCEONLY,UGDS,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,PPTUG_EF,CURROPER,PCTPELL,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GRAD_DEBT_MDN_SUPP
INSTNM,,,,,,,,,,,,,,,,,,,,,,,,,,
University of Alaska Anchorage,Anchorage,AK,0.0,0.0,0.0,0,NaN,NaN,0.0,12865.0,0.5747,0.0358,0.0761,0.0778,0.0653,0.0086,0.0980,0.0181,0.0457,0.4539,1,0.2385,0.2647,0.4386,42500,19449.5
University of Alaska Fairbanks,Fairbanks,AK,0.0,0.0,0.0,0,NaN,NaN,0.0,5536.0,0.4259,0.0210,0.0522,0.0126,0.1284,0.0027,0.0401,0.0110,0.3060,0.3887,1,0.2263,0.2550,0.4519,36200,19355
Charter College-Anchorage,Anchorage,AK,0.0,0.0,0.0,0,NaN,NaN,0.0,3256.0,0.4373,0.0599,0.3093,0.0123,0.0405,0.0577,0.0436,0.0000,0.0393,0.0000,1,0.8307,0.7503,0.5472,39200,13875
University of Alaska Southeast,Juneau,AK,0.0,0.0,0.0,0,NaN,NaN,0.0,1428.0,0.4748,0.0119,0.0623,0.0357,0.1029,0.0147,0.0686,0.0049,0.2241,0.5112,1,0.1769,0.1996,0.5550,37400,16875
AVTEC-Alaska's Institute of Technology,Seward,AK,0.0,0.0,0.0,0,NaN,NaN,0.0,889.0,0.5388,0.0112,0.0427,0.0157,0.1879,0.0112,0.0529,0.0000,0.1395,0.6817,1,0.0737,0.0664,0.7127,33500,PrivacySuppressed

### Chaining methods with dropna, rank and sort_values

In [10]:
college['SATMTMID'].dropna().rank(ascending=False).sort_values().head(20)

INSTNM
California Institute of Technology              1.0
Harvey Mudd College                             2.5
Massachusetts Institute of Technology           2.5
Washington University in St Louis               4.5
Vanderbilt University                           4.5
University of Chicago                           6.0
Franklin W Olin College of Engineering          8.0
Princeton University                            8.0
Harvard University                              8.0
Yale University                                11.0
Carnegie Mellon University                     11.0
Rice University                                11.0
University of Illinois at Urbana-Champaign     15.0
Columbia University in the City of New York    15.0
Stanford University                            15.0
Northwestern University                        15.0
Duke University                                15.0
University of Pennsylvania                     18.5
Webb Institute                                 18.5
Johns Hopkins University                       21.0
Name: SATMTMID, dtype: float64

In [11]:
college['SATMTMID'].dropna() \
                   .rank(ascending=False) \
                   .sort_values() \
                   .head(20)

INSTNM
California Institute of Technology              1.0
Harvey Mudd College                             2.5
Massachusetts Institute of Technology           2.5
Washington University in St Louis               4.5
Vanderbilt University                           4.5
University of Chicago                           6.0
Franklin W Olin College of Engineering          8.0
Princeton University                            8.0
Harvard University                              8.0
Yale University                                11.0
Carnegie Mellon University                     11.0
Rice University                                11.0
University of Illinois at Urbana-Champaign     15.0
Columbia University in the City of New York    15.0
Stanford University                            15.0
Northwestern University                        15.0
Duke University                                15.0
University of Pennsylvania                     18.5
Webb Institute                                 18.5
Johns Hopkins University                       21.0
Name: SATMTMID, dtype: float64

In [13]:
# sort by the values in the index
college.sort_index().head()

,CITY,STABBR,HBCU,MENONLY,WOMENONLY,RELAFFIL,SATVRMID,SATMTMID,DISTANCEONLY,UGDS,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,PPTUG_EF,CURROPER,PCTPELL,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GRAD_DEBT_MDN_SUPP
INSTNM,,,,,,,,,,,,,,,,,,,,,,,,,,
A & W Healthcare Educators,New Orleans,LA,0.0,0.0,0.0,0,NaN,NaN,0.0,40.0,0.0000,0.9750,0.0250,0.0000,0.0,0.0,0.0000,0.0000,0.0000,0.1250,1,0.7018,0.8596,0.6667,NaN,19022.5
A T Still University of Health Sciences,Kirksville,MO,0.0,0.0,0.0,0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,219800,PrivacySuppressed
ABC Beauty Academy,Garland,TX,0.0,0.0,0.0,0,NaN,NaN,0.0,30.0,0.0000,0.0333,0.0333,0.9333,0.0,0.0,0.0000,0.0000,0.0000,0.0000,0,0.7857,0.0000,0.8286,NaN,PrivacySuppressed
ABC Beauty College Inc,Arkadelphia,AR,0.0,0.0,0.0,0,NaN,NaN,0.0,38.0,0.2895,0.6579,0.0526,0.0000,0.0,0.0,0.0000,0.0000,0.0000,0.2105,1,0.9815,1.0000,0.4688,PrivacySuppressed,16500
AI Miami International University of Art and Design,Miami,FL,0.0,0.0,0.0,0,NaN,NaN,0.0,2778.0,0.0324,0.0198,0.4773,0.0018,0.0,0.0,0.0018,0.0025,0.4644,0.2185,1,0.5507,0.6966,0.3262,29900,31000

In [14]:
# Find the school with the minimum for each column
college.select_dtypes('number').idxmax()

HBCU                                     Alabama A & M University
MENONLY         Yeshiva Ohr Elchonon Chabad West Coast Talmudi...
WOMENONLY                                          Judson College
RELAFFIL                                       Amridge University
SATVRMID                       California Institute of Technology
SATMTMID                       California Institute of Technology
DISTANCEONLY                                   Amridge University
UGDS                                University of Phoenix-Arizona
UGDS_WHITE                 Mr Leon's School of Hair Design-Moscow
UGDS_BLACK                     Velvatex College of Beauty Culture
UGDS_HISP                 Thunderbird School of Global Management
UGDS_ASIAN                    Cosmopolitan Beauty and Tech School
UGDS_AIAN                       Haskell Indian Nations University
UGDS_NHPI                                 Palau Community College
UGDS_2MOR                                           LIU Brentwood
UGDS_NRA         California University of Management and Sciences
UGDS_UNKN       Le Cordon Bleu College of Culinary Arts-San Fr...
PPTUG_EF                  Thunderbird School of Global Management
CURROPER                                 Alabama A & M University
PCTPELL                                  MTI Business College Inc
PCTFLOAN                                   ABC Beauty College Inc
UG25ABV                            Dongguk University-Los Angeles
dtype: object

## take a random sample of your data

In [17]:
college.sample(n=8)

,CITY,STABBR,HBCU,MENONLY,WOMENONLY,RELAFFIL,SATVRMID,SATMTMID,DISTANCEONLY,UGDS,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,PPTUG_EF,CURROPER,PCTPELL,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GRAD_DEBT_MDN_SUPP
INSTNM,,,,,,,,,,,,,,,,,,,,,,,,,,
Stevens-The Institute of Business & Arts,Saint Louis,MO,0.0,0.0,0.0,0,NaN,NaN,0.0,143.0,0.3217,0.6573,0.0140,0.0070,0.0000,0.0000,0.0000,0.0000,0.0000,0.3077,1,0.7412,0.9647,0.5233,26300,32620
Sam Houston State University,Huntsville,TX,0.0,0.0,0.0,0,500.0,505.0,0.0,16819.0,0.5400,0.1875,0.1888,0.0128,0.0046,0.0017,0.0299,0.0128,0.0219,0.1942,1,0.4279,0.5782,0.1710,41100,22208
Indiana University-Purdue University-Fort Wayne,Fort Wayne,IN,0.0,0.0,0.0,0,495.0,495.0,0.0,9314.0,0.8295,0.0510,0.0480,0.0233,0.0021,0.0002,0.0251,0.0159,0.0048,0.2576,1,0.3262,0.4363,0.2112,35200,25500
McKendree University,Lebanon,IL,0.0,0.0,0.0,1,510.0,520.0,0.0,2452.0,0.6909,0.1399,0.0432,0.0110,0.0098,0.0037,0.0188,0.0175,0.0653,0.2060,1,0.3622,0.5611,0.3813,43700,24447.5
Gavilan College,Gilroy,CA,0.0,0.0,0.0,0,NaN,NaN,0.0,4754.0,0.3054,0.0227,0.5610,0.0524,0.0048,0.0040,0.0185,0.0008,0.0303,0.6090,1,0.2713,0.0170,0.4194,25200,9500
Empire Beauty School-State College,State College,PA,0.0,0.0,0.0,0,NaN,NaN,0.0,30.0,0.9000,0.0667,0.0000,0.0000,0.0000,0.0000,0.0333,0.0000,0.0000,0.0000,0,0.4912,0.5088,0.4103,18600,10453.5
Marinello School of Beauty-Concord,Concord,CA,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,18600,10352
Exposito School of Hair Design,Amarillo,TX,0.0,0.0,0.0,0,NaN,NaN,0.0,46.0,0.6087,0.0217,0.3043,0.0217,0.0000,0.0000,0.0435,0.0000,0.0000,0.2609,1,0.7467,0.6267,0.3966,15100,PrivacySuppressed

# Your Turn

### Problem 1
<span  style="color:green; font-size:16px">How many unique state abbreviations are there?</span>

In [27]:
college['STABBR'].nunique()

59

### Problem 2
<span  style="color:green; font-size:16px">What school has the largest population in Texas?</span>

In [36]:
tx_coll=college['STABBR']==('TX')

college[tx_coll].sort_values(['UGDS'],ascending=False).head(1)

,CITY,STABBR,HBCU,MENONLY,WOMENONLY,RELAFFIL,SATVRMID,SATMTMID,DISTANCEONLY,UGDS,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,PPTUG_EF,CURROPER,PCTPELL,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GRAD_DEBT_MDN_SUPP
INSTNM,,,,,,,,,,,,,,,,,,,,,,,,,,
Lone Star College System,The Woodlands,TX,0.0,0.0,0.0,0,NaN,NaN,0.0,59920.0,0.3226,0.1892,0.3527,0.0569,0.0024,0.0,0.0281,0.019,0.0292,0.6863,1,0.3405,0.1984,0.3201,32900,11000

### Problem 3
<span  style="color:green; font-size:16px">Replace all the 0's with 1's</span>

In [7]:
college['HBCU'].replace(0,1).head()

INSTNM
Alabama A & M University               1.0
University of Alabama at Birmingham    1.0
Amridge University                     1.0
University of Alabama in Huntsville    1.0
Alabama State University               1.0
Name: HBCU, dtype: float64

# Solutions

### Problem 1
<span  style="color:green; font-size:16px">How many unique state abbreviations are there?</span>

In [37]:
college['STABBR'].nunique()

59

### Problem 2
<span  style="color:green; font-size:16px">What school has the largest population in Texas?</span>

In [38]:
in_texas = college['STABBR'] == 'TX'
tx_schools = college[in_texas]

In [39]:
tx_schools.sort_values('UGDS', ascending=False).head()

,CITY,STABBR,HBCU,MENONLY,WOMENONLY,RELAFFIL,SATVRMID,SATMTMID,DISTANCEONLY,UGDS,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,PPTUG_EF,CURROPER,PCTPELL,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GRAD_DEBT_MDN_SUPP
INSTNM,,,,,,,,,,,,,,,,,,,,,,,,,,
Lone Star College System,The Woodlands,TX,0.0,0.0,0.0,0,NaN,NaN,0.0,59920.0,0.3226,0.1892,0.3527,0.0569,0.0024,0.0000,0.0281,0.0190,0.0292,0.6863,1,0.3405,0.1984,0.3201,32900,11000
Houston Community College,Houston,TX,0.0,0.0,0.0,0,NaN,NaN,0.0,58084.0,0.1430,0.3182,0.3161,0.0926,0.0020,0.0022,0.0151,0.0911,0.0198,0.7027,1,0.6680,0.3348,0.4751,32500,10750
Texas A & M University-College Station,College Station,TX,0.0,0.0,0.0,0,580.0,615.0,0.0,46941.0,0.6610,0.0278,0.2068,0.0546,0.0028,0.0010,0.0308,0.0131,0.0022,0.1049,1,0.2183,0.3320,0.0308,53900,19000
Tarrant County College District,Fort Worth,TX,0.0,0.0,0.0,0,NaN,NaN,0.0,42189.0,0.4097,0.1951,0.2911,0.0572,0.0047,0.0019,0.0198,0.0088,0.0116,0.6552,1,0.3781,0.3055,0.3680,33600,8700
The University of Texas at Austin,Austin,TX,0.0,0.0,0.0,0,630.0,660.0,0.0,38914.0,0.4603,0.0413,0.2192,0.1895,0.0020,0.0014,0.0346,0.0468,0.0049,0.0730,1,0.2602,0.3818,0.0508,53000,22159.5

In [40]:
# even better
college.loc[college['STABBR'] == 'TX', 'UGDS'].sort_values(ascending=False).head()

INSTNM
Lone Star College System                  59920.0
Houston Community College                 58084.0
Texas A & M University-College Station    46941.0
Tarrant County College District           42189.0
The University of Texas at Austin         38914.0
Name: UGDS, dtype: float64

### Problem 3
<span  style="color:green; font-size:16px">Replace all the 0's with 1's</span>

In [41]:
college.replace(0, 1).head()

,CITY,STABBR,HBCU,MENONLY,WOMENONLY,RELAFFIL,SATVRMID,SATMTMID,DISTANCEONLY,UGDS,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,PPTUG_EF,CURROPER,PCTPELL,PCTFLOAN,UG25ABV,MD_EARN_WNE_P10,GRAD_DEBT_MDN_SUPP
INSTNM,,,,,,,,,,,,,,,,,,,,,,,,,,
Alabama A & M University,Normal,AL,1.0,1.0,1.0,1,424.0,420.0,1.0,4206.0,0.0333,0.9353,0.0055,0.0019,0.0024,0.0019,1.0000,0.0059,0.0138,0.0656,1,0.7356,0.8284,0.1049,30300,33888
University of Alabama at Birmingham,Birmingham,AL,1.0,1.0,1.0,1,570.0,565.0,1.0,11383.0,0.5922,0.2600,0.0283,0.0518,0.0022,0.0007,0.0368,0.0179,0.0100,0.2607,1,0.3460,0.5214,0.2422,39700,21941.5
Amridge University,Montgomery,AL,1.0,1.0,1.0,1,NaN,NaN,1.0,291.0,0.2990,0.4192,0.0069,0.0034,1.0000,1.0000,1.0000,1.0000,0.2715,0.4536,1,0.6801,0.7795,0.8540,40100,23370
University of Alabama in Huntsville,Huntsville,AL,1.0,1.0,1.0,1,595.0,590.0,1.0,5451.0,0.6988,0.1255,0.0382,0.0376,0.0143,0.0002,0.0172,0.0332,0.0350,0.2146,1,0.3072,0.4596,0.2640,45500,24097
Alabama State University,Montgomery,AL,1.0,1.0,1.0,1,425.0,430.0,1.0,4811.0,0.0158,0.9208,0.0121,0.0019,0.0010,0.0006,0.0098,0.0243,0.0137,0.0892,1,0.7347,0.7554,0.1270,26600,33118.5